In [1]:
from keras.models import load_model
from keras.preprocessing.sequence import pad_sequences
from utils.TextPreprocess import clean_text
import pickle
from numpy import argmax
import praw

Using TensorFlow backend.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\abdul\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [3]:
model = load_model(".\models\LSTM\lstm.h5")

In [4]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 500, 100)          6000000   
_________________________________________________________________
dropout_1 (Dropout)          (None, 500, 100)          0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, 496, 64)           32064     
_________________________________________________________________
maxpool_1 (MaxPooling1D)     (None, 124, 64)           0         
_________________________________________________________________
BiLSTM_module (Bidirectional (None, 200)               132000    
_________________________________________________________________
output (Dense)               (None, 11)                2211      
Total params: 6,166,275
Trainable params: 6,166,275
Non-trainable params: 0
____________________________________________

In [2]:
with open("./models/LabelEncoder/LabelEncoder.pkl", 'rb') as fp:
    le = pickle.load(fp)
with open("./models/Tokenizer/tokenizer.pkl", 'rb') as fp:
    tokenizer = pickle.load(fp)

In [3]:
le.classes_

array(['AskIndia', 'Business/Finance', 'Coronavirus', 'Food',
       'Non-Political', 'Photography', 'Policy/Economy', 'Politics',
       'Science/Technology', 'Sports', '[R]eddiquette'], dtype=object)

In [8]:
reddit = praw.Reddit(
        client_id='pw8WCM92ySUjsQ', 
        client_secret='y0MJFMWBtHXMLW2-3B2upsU2jYQ', 
        user_agent='reddit-scrap', 
        username='macabdul9', 
        password='Sudo$0#1'
)

In [9]:
url =  "https://www.reddit.com/r/india/comments/g79auq/greetings_from_saudi_arabia_during_this_lock_down/"

In [5]:
# data

In [34]:
len(data)

1

array([[0.02533309, 0.00603649, 0.51029295, 0.00445003, 0.13989675,
        0.00242763, 0.03338875, 0.25958517, 0.00629901, 0.00871575,
        0.00357436]], dtype=float32)

2

In [39]:
le.classes_

array(['AskIndia', 'Business/Finance', 'Coronavirus', 'Food',
       'Non-Political', 'Photography', 'Policy/Economy', 'Politics',
       'Science/Technology', 'Sports', '[R]eddiquette'], dtype=object)

In [10]:
def get_pred(url):
    sub = reddit.submission(url=url)
    data = " ".join([sub.title, sub.url, sub.selftext, sub.link_flair_text])
    data = clean_text(data)
    return data
    ### Create sequence
    # sequences = tokenizer.texts_to_sequences([data])
    # data = pad_sequences(sequences, maxlen=500)
    # return le.classes_[argmax(model.predict(data))]

In [11]:
data = get_pred(url="https://www.reddit.com/r/india/comments/g7gjg2/dear_indians_today_armenians_all_around_the_world/")

In [12]:
from multiprocessing import cpu_count

In [13]:
args = {
    "output_dir": "outputs-xlnet/",
    "cache_dir": "cache-xlnet/",
    "best_model_dir": "outputs-xlnet/best_model/",

    "fp16": False,
    "fp16_opt_level": "O1",
    "max_seq_length": 128,
    "train_batch_size": 32,
    "eval_batch_size": 32,
    "gradient_accumulation_steps": 1,
    "num_train_epochs": 3,
    "weight_decay": 0,
    "learning_rate": 1e-4,
    "adam_epsilon": 1e-8,
    "warmup_ratio": 0.06,
    "warmup_steps": 0,
    "max_grad_norm": 1.0,
    "do_lower_case": False,

    "logging_steps": 50,
    "evaluate_during_training": False,
    "evaluate_during_training_steps": 2000,
    "evaluate_during_training_verbose": False,
    "use_cached_eval_features": False,
    "save_eval_checkpoints": True,
    "no_cache": False,
    "save_model_every_epoch": True,
    "tensorboard_dir": None,

    "overwrite_output_dir": True,
    "reprocess_input_data": True,

    "process_count": cpu_count() - 4 ,
    "n_gpu": 1,
    "silent": False,
    "use_multiprocessing": True,

    "wandb_project": None,
    "wandb_kwargs": {},

    "use_early_stopping": True,
    "early_stopping_patience": 2,
    "early_stopping_delta": 0,
    "early_stopping_metric": "eval_loss",
    "early_stopping_metric_minimize": True,

    "manual_seed": 0,
    "encoding": None,
    "config": {},
}

In [14]:
from simpletransformers.classification import ClassificationModel

In [16]:
model = ClassificationModel("distilbert", './models/DistilBERT/checkpoint-3530-epoch-5', use_cuda=False, num_labels=11)

In [17]:
predictions, raw_outputs = model.predict([data])

100%|██████████| 1/1 [00:00<00:00,  7.87it/s]


In [21]:
predictions[0]

7

In [33]:
import numpy as np

In [45]:
top_3 = raw_outputs.argsort()[0][-3:]


array([10,  4,  7], dtype=int64)

In [46]:
raw_outputs

array([[-2.0442946, -6.101591 , -5.9006543, -7.1868215,  5.3623037,
        -6.0955386, -1.851397 ,  7.4698653, -5.8149967, -3.8449247,
         0.5095671]], dtype=float32)

In [49]:
def softmax_numpy(scores):
  return np.exp(scores)/sum(np.exp(scores), axis=0)

In [59]:
confidence = softmax_numpy(raw_outputs[0])

In [61]:
confidence[0]

6.573594e-05

In [1]:
import requests

In [10]:
URL = "https://young-oasis-17864.herokuapp.com/"
PARAMS = {'url':"https://www.reddit.com/r/india/comments/g7qeec/doland_dont_do_press_conference/"}

In [12]:
# sending get request and saving the response as response object 
r = requests.post(url = URL, params = PARAMS) 
  
# extracting data in json format 
# data = r.json() 

In [13]:
print(r)

<Response [503]>
